INSERT INTO series (title, author_ID, subgenre_ID) VALUES ("LOTR", 1, 1);
INSERT INTO series (title, author_ID, subgenre_ID) VALUES ("Harry Potter", 2, 1);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO books (title, year, series_id) VALUES ("The Test", 1985, 2);
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO characters (name, motto, species, author_ID, series_id) VALUES ("Merlin", "Poof", "human", 2, 3 );
INSERT INTO subgenres (name) VALUES ("Medieval Times");
INSERT INTO subgenres (name) VALUES ("historical fiction");
INSERT INTO authors (name) VALUES ("Tom Clancey");
INSERT INTO authors (name) VALUES ("Stephen King");
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
INSERT INTO character_books(character_id, book_id) VALUES (1,2);
